### ISSUE TITLE
Record Tracking - Firebase

### ISSUE THREAD

**Issue by lewis00001** [lewis00001/tempic#10]
## Purpose
Create two variables on firebase to help the record information

## Acceptance
- [ ] create a variable for person's name for low number of tries
- [ ] create a variable for the person's name for the lowest amount of time
- [ ] create a variable for the lowest number of tries
- [ ] create a variable for the lowest amount of time
- [ ] added the firebase config information to the top of the app.js file
