### ISSUE TITLE
Setup City.js

### ISSUE THREAD

**Issue by jgohbb** [lewis00001/tempic#29]
## Tasks:
- [x] Populate info for country, city and link images.
- [x] Retrieve and insert economics data (cancelled - not a good fit for this project)
- [x] Retrieve population by cities
- [x] created new element - annual sunshine hours - retrieve and insert
